<?php

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Dashboard',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2017-12-04 00:33:35',
                'updated_at' => '2017-12-04 00:33:35',
                'route' => 'voyager.dashboard',
                'parameters' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2017-12-04 00:33:35',
                'updated_at' => '2017-12-10 04:57:41',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Posts',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-news',
                'color' => NULL,
                'parent_id' => 19,
                'order' => 1,
                'created_at' => '2017-12-04 00:33:35',
                'updated_at' => '2017-12-12 11:04:43',
                'route' => 'voyager.posts.index',
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2017-12-04 00:33:35',
                'updated_at' => '2017-12-04 00:33:35',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Blog Categories',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-categories',
                'color' => '#000000',
                'parent_id' => 19,
                'order' => 2,
                'created_at' => '2017-12-04 00:33:35',
                'updated_at' => '2017-12-12 11:04:47',
                'route' => 'voyager.categories.index',
                'parameters' => 'null',
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Pages',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-file-text',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2017-12-04 00:33:35',
                'updated_at' => '2017-12-12 11:04:32',
                'route' => 'voyager.pages.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2017-12-04 00:33:35',
                'updated_at' => '2017-12-04 00:33:35',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2017-12-04 00:33:35',
                'updated_at' => '2017-12-12 11:04:36',
                'route' => NULL,
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 8,
                'order' => 1,
                'created_at' => '2017-12-04 00:33:36',
                'updated_at' => '2017-12-10 04:57:41',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 8,
                'order' => 2,
                'created_at' => '2017-12-04 00:33:36',
                'updated_at' => '2017-12-10 04:57:41',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '/admin/compass',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 8,
                'order' => 3,
                'created_at' => '2017-12-04 00:33:36',
                'updated_at' => '2017-12-10 04:57:41',
                'route' => NULL,
                'parameters' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'menu_id' => 1,
                'title' => 'Hooks',
                'url' => '/admin/hooks',
                'target' => '_self',
                'icon_class' => 'voyager-hook',
                'color' => NULL,
                'parent_id' => 8,
                'order' => 4,
                'created_at' => '2017-12-04 00:33:36',
                'updated_at' => '2017-12-10 04:57:41',
                'route' => NULL,
                'parameters' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 11,
                'created_at' => '2017-12-04 00:33:36',
                'updated_at' => '2017-12-29 03:38:27',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'Sliders',
                'url' => '/admin/sliders',
                'target' => '_self',
                'icon_class' => 'voyager-photo',
                'color' => '#000000',
                'parent_id' => 21,
                'order' => 2,
                'created_at' => '2017-12-07 17:45:10',
                'updated_at' => '2017-12-29 03:59:57',
                'route' => NULL,
                'parameters' => '',
            ),
            14 => 
            array (
                'id' => 15,
                'menu_id' => 1,
                'title' => 'Product Categories',
                'url' => '/admin/product-categories',
                'target' => '_self',
                'icon_class' => 'voyager-archive',
                'color' => '#000000',
                'parent_id' => 18,
                'order' => 2,
                'created_at' => '2017-12-07 18:24:09',
                'updated_at' => '2017-12-10 05:06:13',
                'route' => NULL,
                'parameters' => '',
            ),
            15 => 
            array (
                'id' => 16,
                'menu_id' => 1,
                'title' => 'Items',
                'url' => '/admin/products',
                'target' => '_self',
                'icon_class' => 'voyager-bag',
                'color' => '#000000',
                'parent_id' => 18,
                'order' => 1,
                'created_at' => '2017-12-08 06:26:03',
                'updated_at' => '2017-12-10 05:06:36',
                'route' => NULL,
                'parameters' => '',
            ),
            16 => 
            array (
                'id' => 17,
                'menu_id' => 1,
                'title' => 'Product Brands',
                'url' => '/admin/product-brand',
                'target' => '_self',
                'icon_class' => 'voyager-certificate',
                'color' => NULL,
                'parent_id' => 18,
                'order' => 3,
                'created_at' => '2017-12-10 04:50:20',
                'updated_at' => '2017-12-10 05:06:14',
                'route' => NULL,
                'parameters' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'menu_id' => 1,
                'title' => 'Product',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2017-12-10 05:05:50',
                'updated_at' => '2017-12-29 03:38:27',
                'route' => NULL,
                'parameters' => '',
            ),
            18 => 
            array (
                'id' => 19,
                'menu_id' => 1,
                'title' => 'Blog',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-browser',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 10,
                'created_at' => '2017-12-12 11:04:22',
                'updated_at' => '2017-12-29 03:38:27',
                'route' => NULL,
                'parameters' => '',
            ),
            19 => 
            array (
                'id' => 20,
                'menu_id' => 1,
                'title' => 'Categories',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-categories',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2017-12-15 00:49:05',
                'updated_at' => '2017-12-15 01:43:14',
                'route' => 'voyager.categories.index',
                'parameters' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'menu_id' => 1,
                'title' => 'Ecommerce',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-shop',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2017-12-15 01:42:41',
                'updated_at' => '2017-12-15 01:47:47',
                'route' => NULL,
                'parameters' => '',
            ),
            21 => 
            array (
                'id' => 23,
                'menu_id' => 1,
                'title' => 'Bank Accounts',
                'url' => '/admin/bank-account',
                'target' => '_self',
                'icon_class' => 'voyager-wallet',
                'color' => '#000000',
                'parent_id' => 21,
                'order' => 3,
                'created_at' => '2017-12-29 03:48:36',
                'updated_at' => '2017-12-29 03:50:59',
                'route' => NULL,
                'parameters' => '',
            ),
            22 => 
            array (
                'id' => 24,
                'menu_id' => 1,
                'title' => 'Orders',
                'url' => '/admin/orders',
                'target' => '_self',
                'icon_class' => 'voyager-basket',
                'color' => '#000000',
                'parent_id' => 21,
                'order' => 1,
                'created_at' => '2017-12-29 03:59:20',
                'updated_at' => '2017-12-29 04:00:15',
                'route' => NULL,
                'parameters' => '',
            ),
            23 => 
            array (
                'id' => 25,
                'menu_id' => 1,
                'title' => 'Couriers',
                'url' => '/admin/courier',
                'target' => '_self',
                'icon_class' => 'voyager-truck',
                'color' => '#000000',
                'parent_id' => 21,
                'order' => 4,
                'created_at' => '2017-12-29 05:37:24',
                'updated_at' => '2017-12-29 05:55:47',
                'route' => NULL,
                'parameters' => '',
            ),
            24 => 
            array (
                'id' => 26,
                'menu_id' => 1,
                'title' => 'Payment Channels',
                'url' => '/admin/payment-channel',
                'target' => '_self',
                'icon_class' => 'voyager-credit-cards',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 12,
                'created_at' => '2018-01-03 15:43:52',
                'updated_at' => '2018-01-03 15:44:14',
                'route' => NULL,
                'parameters' => '',
            ),
            25 => 
            array (
                'id' => 27,
                'menu_id' => 1,
                'title' => 'Email Templates',
                'url' => '/admin/email-template',
                'target' => '_self',
                'icon_class' => 'voyager-mail',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 13,
                'created_at' => '2018-01-04 19:19:12',
                'updated_at' => '2018-01-04 19:19:12',
                'route' => NULL,
                'parameters' => NULL,
            ),
        ));
        
        
    }
}