<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'role_id' => 1,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Admin',
                'email' => 'admin@admin.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$zIuPZYhTjkuZwcPbGfXw7.dO.pJBqgFGmvWyqXLQsBNvm.cukYehq',
                'verified' => 0,
                'email_token' => NULL,
                'remember_token' => 'ONAyoSCf4iYyC6me5flJ6M5tO3SiBOiIVLU39vDadF8DVLnO9SblNC5oaYwc',
                'created_at' => '2017-12-03 22:59:47',
                'updated_at' => '2017-12-03 22:59:47',
            ),
            1 => 
            array (
                'id' => 15,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => '11',
                'name' => 'CodeHub ID',
                'email' => 'rizal@codehub.id',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$gKl9/Z/TBbpVVLgNzgXR2Oib8Go0jm7ECcNhoFEWGUqzdRo1vZnzC',
                'verified' => 0,
                'email_token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2017-12-07 17:31:52',
                'updated_at' => '2017-12-07 17:31:52',
            ),
            2 => 
            array (
                'id' => 17,
                'role_id' => 3,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Admin Biogreen',
                'email' => 'admin@bio.dev',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$0QZUNtGyZHstdZ01qlVCg.SWlGr0PdF9e5rh1GXcaCBh09PaNwVj.',
                'verified' => 0,
                'email_token' => NULL,
                'remember_token' => 'CxDSAVWLpk2LIdMofDpMWqUncHO28kLDzVD3fNuSgqBqxRKDlDN2AdUjUdUS',
                'created_at' => '2017-12-07 17:52:14',
                'updated_at' => '2017-12-07 17:52:14',
            ),
            3 => 
            array (
                'id' => 18,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'test@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$cGxm5T0KEZgkEtxeH3EGKemeLLmNSXlCRlIFt3QIl41fzPl3TCgA2',
                'verified' => 0,
                'email_token' => NULL,
                'remember_token' => '0j7ncBSk571emfDW2ky83xuzLcVdIaZQsZrdEreeprUQjyuQ86qQF9j8gQ0C',
                'created_at' => '2017-12-08 16:31:41',
                'updated_at' => '2017-12-12 10:52:14',
            ),
            4 => 
            array (
                'id' => 19,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'rrrr',
                'email' => 'tesst@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$u5mIP6dKg781WKIf6FW4nuL6L9R.U/UJqyP6NFCUTgyFh6rxGVac.',
                'verified' => 0,
                'email_token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2017-12-08 16:46:32',
                'updated_at' => '2017-12-08 16:46:32',
            ),
            5 => 
            array (
                'id' => 20,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'dfsdf',
                'email' => 'aa@ggmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$KCcdJdf4I90qHlgm.HC9CuNGqdxRfy/2t/YmNCe51tuzyigSPYO/S',
                'verified' => 0,
                'email_token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2017-12-08 16:47:17',
                'updated_at' => '2017-12-08 16:47:17',
            ),
            6 => 
            array (
                'id' => 21,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'dfsdf',
                'email' => 'sdgsdfg@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$ORiWorh5kpGBjIsh1sAeX.M4jACV1cT9gFXJSBfRr0VGzU7a49TeW',
                'verified' => 0,
                'email_token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2017-12-08 16:51:54',
                'updated_at' => '2017-12-08 16:51:54',
            ),
            7 => 
            array (
                'id' => 22,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'ass',
                'email' => 'mm@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$B2jRMHytGELQFjp5eYXsqOvo3rTNYQdAw/0ZCZI243OD6NbzPhetS',
                'verified' => 0,
                'email_token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2017-12-08 16:53:04',
                'updated_at' => '2017-12-08 16:53:05',
            ),
            8 => 
            array (
                'id' => 23,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'dsfa',
                'email' => 'AAA@HMAIL.COM111111',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$sXRbbu3coPo.dpeeFLW80u0yI20JfCpjmERI0mBHFHzn2/pdJlh16',
                'verified' => 0,
                'email_token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2017-12-08 16:54:31',
                'updated_at' => '2017-12-08 16:54:31',
            ),
            9 => 
            array (
                'id' => 24,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'dsf',
                'email' => 'asa@gma.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$MTrjbHcpkuRdZLrTgvnarO1GgKQWKB.W/7ZkzoTynLVF3zsMbew1a',
                'verified' => 0,
                'email_token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2017-12-08 16:55:18',
                'updated_at' => '2017-12-08 16:55:18',
            ),
            10 => 
            array (
                'id' => 25,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'dsf',
                'email' => 'aaaaa@h.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$1No4gvQ7Wj86hbEfjeg64.ygvP/.Sf/mqF83ej3t4gk3xUwwSi7a6',
                'verified' => 0,
                'email_token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2017-12-08 16:57:14',
                'updated_at' => '2017-12-08 16:57:14',
            ),
            11 => 
            array (
                'id' => 26,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'dsf',
                'email' => 'aas@g.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$9cBFifgsCBWdB41N2MT65uLqpcT3yCw3yjOTizp0jEocWbSn8zAfy',
                'verified' => 0,
                'email_token' => 'eyJpdiI6Ik9wazAwVXlNQ3NRajRWVkZ1bUkwbWc9PSIsInZhbHVlIjoiQTNBbTN1K05hT2w4ejI0XC9HTVZCbDdZOTRqT2Y2WFwvUDhPSmN6ckZ6ajJRPSIsIm1hYyI6IjhjNDFjYmU1NDdjYmRiYjdhM2I3NGE0MDJhNjAzNThjNmJjY2IwN2E1ODI5Yzk1NzZiNzA1YmZiM2YyYWQ3MTcifQ==',
                'remember_token' => NULL,
                'created_at' => '2017-12-08 16:58:14',
                'updated_at' => '2017-12-08 16:58:14',
            ),
            12 => 
            array (
                'id' => 27,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'sadkjashdkj',
                'email' => 'aaaaa@aaa.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$8pUHbtNcilbVrE8rWbUDl.b/vOkldaMet39FrNc3Z1npgpplI9gc6',
                'verified' => 0,
                'email_token' => 'eyJpdiI6InBwSzZueU4zWTd5WlZ6eE9IYUN2SlE9PSIsInZhbHVlIjoiZ1JYTXYralwvUER1U3I1ZWdIak53VVdzcCt4bTRCQWhmMmVOK0JaRGtBNm89IiwibWFjIjoiNTM2YjRlOTNiNDQ3NTZmNDkzZGE1ODEwYzJiODYzZDljNjEwYTY5NTY2MzBmNjY3NGNkNWY2NTRjMmEzYjk4MyJ9',
                'remember_token' => NULL,
                'created_at' => '2017-12-08 17:16:06',
                'updated_at' => '2017-12-08 17:16:06',
            ),
            13 => 
            array (
                'id' => 28,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'pasti bisa',
                'email' => 'bisa@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$kP.lLsFbXsikUArMEduyZeyr6mkG/XfDizrefm37aTVolIgOymwom',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IllLVjNBXC9WNFwvQmx5Q3g5K0kyWGZcL1E9PSIsInZhbHVlIjoicUM2OE9rbUFuQmVpajlZMndMSk5RYmdFakJaM0J5R2dYT2ppNTN6SmVFYz0iLCJtYWMiOiJhOTIxZTUxZTFkZTcxNDg3MzM5ZTc5YzU0NWE4OGI0YTkyZDQ1Y2YyOGYzODI0MzlmMDk5ZTY2YzBkNzUzYmRhIn0=',
                'remember_token' => NULL,
                'created_at' => '2017-12-08 17:17:07',
                'updated_at' => '2017-12-08 17:17:07',
            ),
            14 => 
            array (
                'id' => 29,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'bisa 2',
                'email' => 'bisa2@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$zO6U0eC6ad06cFswIOUyGOML8X3PLbogBrc5kk2CxcyHCx7QBDv7S',
                'verified' => 0,
                'email_token' => 'eyJpdiI6InFVK2NzQkFlQ09PNTVLOWptcW93R2c9PSIsInZhbHVlIjoiR0ZFZUhNV3d6WkZOd29zUU5qWmcrUDViWUowSk1COWJ3d1NLY0gxc3ZhTT0iLCJtYWMiOiIwYTZkN2MwN2EzNGI4ODIzMWU3NzNmZDhlMmM5MzRjMDE3ZjE3MWM1NzZhZTJkMzliMTMxYzc1ZDRiNmZhYTU1In0=',
                'remember_token' => NULL,
                'created_at' => '2017-12-08 17:19:25',
                'updated_at' => '2017-12-08 17:19:25',
            ),
            15 => 
            array (
                'id' => 30,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'bisa 3',
                'email' => 'bisa3@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$2na0xL6ePMF.somejoDjluD0FUStBefqd3rx.cr7K4/xC1iUneEpi',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IjRLaVJnbHpHVnRiSDM2aTlJblJwenc9PSIsInZhbHVlIjoiS2tRK3RhWTVSNVcwY3p6QTBQR2tLK1paZlcxdmhMM2E4VkE2ViszOXJCdz0iLCJtYWMiOiI2Nzk4OTU5ZDY2ZDFiZTZiNWUyMTkyMWQwYzljNzUwZDFhMzY4MTc2NTNjZGNiYTM0ZDE3MzhlZjhjNWQ4NTVlIn0=',
                'remember_token' => NULL,
                'created_at' => '2017-12-08 17:21:18',
                'updated_at' => '2017-12-08 17:21:18',
            ),
            16 => 
            array (
                'id' => 31,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'mnmn',
                'email' => 'mn@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$iBK.beoy2TGbNsmmMIOaDunAAjgqVxTYQByyQX/sPSC3SLICzQyoi',
                'verified' => 0,
                'email_token' => 'eyJpdiI6ImNnSnZoaDE0NkE4a2hOQzI4UHh2TlE9PSIsInZhbHVlIjoieGV1Z1pEZHozZElHU2xIaEY2RGxBZjJwRWtoWlp5KzRvM2ZzN3BySHRkUT0iLCJtYWMiOiJhY2RkZWY3MjY1NDIyMzgzNzNhN2QzZTNlZjM1YzI5MWE5NGZhZjIyNGNiYjRhOTRhOGZkNjJjZjFhM2E2OWJkIn0=',
                'remember_token' => NULL,
                'created_at' => '2017-12-08 18:48:28',
                'updated_at' => '2017-12-08 18:48:28',
            ),
            17 => 
            array (
                'id' => 32,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'bisa dong',
                'email' => 'bis@g.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$pIrkGqQY275DcYj4SQy5E.46Y4NyB8l19Rx1tjvShPqOCsV7o7M5S',
                'verified' => 0,
                'email_token' => 'eyJpdiI6Ijh2WWdFbmVWOFJqYkFTODd0ZlwvRVRRPT0iLCJ2YWx1ZSI6ImE3SWRTN28wZ083ZXp5VzJqNWh3VUJacEZpXC9SYWtpaHRQdGl3eGVkZG40PSIsIm1hYyI6ImJhOTlmMTQyYTUyOTkyZDFmZjAxMmU3MzJkMDYwYjU3YzU0YmVkOGQyYzA0ZWViZWZhZWZlZDZiZTgxNzgyN2MifQ==',
                'remember_token' => NULL,
                'created_at' => '2017-12-08 18:50:26',
                'updated_at' => '2017-12-08 18:50:26',
            ),
            18 => 
            array (
                'id' => 34,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => '14',
                'name' => 'Rizal Fakhri',
                'email' => '31122000rizal@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$pBbY5i7DnVLVAdUw6jiMpusRPMPHuqR0eKAa1kB02uD1a6ogE1/pK',
                'verified' => 0,
                'email_token' => NULL,
                'remember_token' => 'd0lVof6OsfTtwnt4qwbGpKke8gy0wBXHIxPC0sWa1XOJ7PJvAoctrGC8zMKC',
                'created_at' => '2017-12-08 20:27:09',
                'updated_at' => '2017-12-08 20:27:09',
            ),
            19 => 
            array (
                'id' => 35,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'blabla',
                'email' => 'bl@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$02BLTQe7cpk2pZpj/uv8EOaoIL3E9MWoe8.zWO/fJ3S8GOK..sRfm',
                'verified' => 0,
                'email_token' => 'eyJpdiI6Img5b3pQdkZ5QjAwUlwvMU81V3dXdjh3PT0iLCJ2YWx1ZSI6IitYZVl4emh1WDNGblZBaTljaE5TMlwvait5a3NUWUdiMVZ5ZEJKS1VBbmpzPSIsIm1hYyI6IjUzMjhmM2Y2Y2E1YThhMDIwZjlmZDhiNDlhYTUxMzk5NmUzZDljZDQ4MTE2ZmZlMmYyZWUyOTM3NzI3YWE2MTQifQ==',
                'remember_token' => NULL,
                'created_at' => '2017-12-08 17:18:45',
                'updated_at' => '2017-12-08 17:18:46',
            ),
            20 => 
            array (
                'id' => 36,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Test Nama',
                'email' => 'test@g.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$gAmPNCOAM.WRX//52eOXV.QjV6FXRSvcqqqvTalqbe4keDwG.mWSS',
                'verified' => 1,
                'email_token' => 'eyJpdiI6IjNEVUlxYUZsTHFvZ25lUlBvTVZOXC9BPT0iLCJ2YWx1ZSI6IktnSElSTTN2Y1VNUVNCV24ydmI4XC9QblwvWHYwd1o4MThjVFJ6WW4rK2xvaz0iLCJtYWMiOiJjNGVhMThiZTc1Y2NkZmZmZDBhNWEwZmVmODcxNWI1OGFlMWYyY2UzMDVlMTg3ZGFkYTQzYTFmMDU0MzViODE0In0=',
                'remember_token' => NULL,
                'created_at' => '2017-12-10 00:08:41',
                'updated_at' => '2017-12-10 01:04:48',
            ),
            21 => 
            array (
                'id' => 37,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'H',
                'email' => 'p@h.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$JRKnKk9TOKnZnOGE7uhLTORpG/BXPoceHxLNzLoNwgnULgTG/g5ym',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IlwvXC9yVW9zYlMwVlwvWDBwK1NKVlwvV3h3PT0iLCJ2YWx1ZSI6IlkyRjYzUlRyWkJiVjZrdTJueDJ5UHc9PSIsIm1hYyI6IjM1NzA4ZGY3NmVjMDljYjAxYTNmNzYzYzBiOTAzZjUwMWRmMTVkM2I5NGE1YmNlOGEwNTI0ZTVkZDhiMjA1MzYifQ==',
                'remember_token' => NULL,
                'created_at' => '2017-12-23 02:03:23',
                'updated_at' => '2017-12-23 02:03:23',
            ),
            22 => 
            array (
                'id' => 38,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'n',
                'email' => 'n@g.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$ygZoG5MLfYcQ.b4n1CarYezeknsSN2cb8gaoR88t99WtlW4y5qVh2',
                'verified' => 0,
                'email_token' => 'eyJpdiI6Imd2SW81QjZhZmU2S3VIQ1J3WituQ1E9PSIsInZhbHVlIjoiaHBtb2JcL0taVkJ3NWFcL1h5MkFYeUV3PT0iLCJtYWMiOiIzNzlkYzkxOTE2MDg3MjI4ZGRkYWMxMmJiY2ZhOWI0MmJjODI4YTdhYzM3NDYxZjE1NDUxODA5MjA1YzU0MjQ5In0=',
                'remember_token' => NULL,
                'created_at' => '2017-12-23 02:08:58',
                'updated_at' => '2017-12-23 02:08:58',
            ),
            23 => 
            array (
                'id' => 39,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => '15',
                'name' => 'Rizal Fakhri',
                'email' => 'rizalfakhri12@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$wXnuzlw7lh4H5DnM0aNH3eRzIJLALkkPUiVAqYStb2bUXVfoqjEO.',
                'verified' => 0,
                'email_token' => NULL,
                'remember_token' => 'w7ELd8BBAkZeyhCc9d26Z2v6GQ1svXtzSuHJNl1NVEiNJqYLKfQZtOHQxtHu',
                'created_at' => '2017-12-24 02:34:24',
                'updated_at' => '2017-12-30 05:27:06',
            ),
            24 => 
            array (
                'id' => 40,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'RIzal Ganteng',
                'email' => 'r@g.anteng',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$.O4Uurm51RzXd2FfOApSfu0/VukUDZaZenMk/B0ZKHAiLBaK4t9e6',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IjZEWnE5dTdNbytua2pwTDRJK0NNNGc9PSIsInZhbHVlIjoia2NPcXd2QWpxNlwvZlE1XC9cL29XZ0ZraGRHQVNua1BRTDJWRkJpUzgrSGNKZz0iLCJtYWMiOiJmOGFmZjg0Y2FmZWQ4ZTc5NmM4NmY3NzE2OGI2YWFkYjYwN2ZmZTI4OWZjMjAxZGI2MGFkMzAxNWE0ZDFhMGIzIn0=',
                'remember_token' => 'NZbPyewxkvScuzLejqkuZN24FytViOgXECP8h0mGHgonDUOq5HfxglV90W3T',
                'created_at' => '2017-12-24 02:36:05',
                'updated_at' => '2017-12-24 02:36:05',
            ),
            25 => 
            array (
                'id' => 41,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'rizal@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$MtYEJXHt09yhcoBk1bSBEOmqObWcQQw1BVcwhjK7J0FyKWrf6jTnS',
                'verified' => 0,
                'email_token' => 'eyJpdiI6Im5OeW4yd2xzc01HTjZoaUN6bDU4MVE9PSIsInZhbHVlIjoiY0VhQnR1Szg5dkpPZExXR0hKVklkY1FZRXlwNlAwSnNSRU02MW5naEJoaz0iLCJtYWMiOiIyNTYzZmEwNDRkYzlhZmQxM2U4MDkxYmExYjZmM2RjOTlkODRjM2RiMmZmYzkzNTk4M2EzYjAwNzQ1NGRjMzFkIn0=',
                'remember_token' => 'HWZoQcidq3yDu2ZQOyILwQ4VknE6i5ANL3rKsjt3WzlMyUZbYbvhyn0ZdjKE',
                'created_at' => '2018-01-03 13:12:42',
                'updated_at' => '2018-01-03 13:12:42',
            ),
            26 => 
            array (
                'id' => 42,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Test',
                'email' => 'dyn@email.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$OTNVUZImxCH8t3kMFtOGoeN1QWW6QIBLsyisqpnkp6...fDL0xCdG',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IitGblBkZHJmMWlzazRiSzAzMk9VMXc9PSIsInZhbHVlIjoiZHNPSnVOWG85OGtOZ3pwOHJ5YkpLOEZxN29VUGE4QlBvUTkreTZTc2RIcz0iLCJtYWMiOiI4YzBmMjMxZjEyZTE5ZGYzZjNiOWEyZGIzYWRiMGZlYzUwNTMwYmQ5MzI4MGQ3ZTliMjVjMmNkODIyMDFmYjg3In0=',
                'remember_token' => 'HpyQOYiYwCiYvNwuGyh3YlOgDTSNCrhBr1UCbqhMDJsqX6sIPiMo8DnQXgjQ',
                'created_at' => '2018-01-08 10:09:05',
                'updated_at' => '2018-01-08 10:09:05',
            ),
            27 => 
            array (
                'id' => 43,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Pasti BIsa',
                'email' => 'bisa20@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$6hjwhIlLUxM4vhFosy6.AuAyLYsAGc8V/WggCZ5DAMJuCDwjVI5J2',
                'verified' => 0,
                'email_token' => 'eyJpdiI6InMrSFNDSlMrVmVtQTgxaVlkSCtJSEE9PSIsInZhbHVlIjoia0tpYXlzVkdlOEFONmRhYWNKSHRpUlRDeU5EVHFRanRJdXhNMlppM3htaz0iLCJtYWMiOiJhMDQwMjM2MmI2YmVhZjhiZTM4NWY2OTdkNGU0NjM3N2JkNWI3YzdlNzg3Yzc3ZGYyYWZkMGZhOGUyNTVjYzM5In0=',
                'remember_token' => 'mXj98kBQYLENNL5LDje31TPQ6ixz1NjKU71GTkcydCTnmwBF7wDigseKWXOX',
                'created_at' => '2018-01-08 10:21:51',
                'updated_at' => '2018-01-08 10:21:51',
            ),
            28 => 
            array (
                'id' => 44,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'BIsa Kan',
                'email' => 'bisa21@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$NJx7h4RsB6kkwAneXLkV9OVgHBHnazGO6vhIEgv2UMlWyNxXI4ewy',
                'verified' => 0,
                'email_token' => 'eyJpdiI6InE3Zncxc3VxOXNcL3lUWTFvVVpmSXVRPT0iLCJ2YWx1ZSI6IkNzRFg2XC91TGR1UHhQdDNvV2pyOXRHZUt1aWxkdmVBa3J3MUhJazdJQmZvPSIsIm1hYyI6IjI1OTcxYWRhYmNhMGE2MTg2MmZiMDczNjg4YzIzMTA1ODc1YWIzMmZjMmIzODk4YWVkNjhhMWY3ZmZiY2E0NDkifQ==',
                'remember_token' => '70KqSLUcuaHgX0gZ51yjUxoDnok47O0TR3Fsfube5R4fH8XuGJpmf68F5WwE',
                'created_at' => '2018-01-08 10:22:56',
                'updated_at' => '2018-01-08 10:22:56',
            ),
            29 => 
            array (
                'id' => 45,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Sekarang Bisa',
                'email' => 'sekarangbisa@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$B3hcR.jI5Yan3ygLFFaAV.74rlpW2dPcvSWsywGdvXV2WGujO1D6G',
                'verified' => 0,
                'email_token' => 'eyJpdiI6Ik1SUEQxMHhyblBvRzZXSUZlbThSeHc9PSIsInZhbHVlIjoieTZqSGxjWjJXWit3ekpVRG5DVmZcL2pJXC96Q2VxWlltTll4eGpsVVk2Q2pBPSIsIm1hYyI6ImM1Yzc0YThiM2FiY2E0MGQxMjhjMTU3ZDZlMmM2YWZkNDk3NDYzNGEwNGJiNjYwMWE2Y2NlMjcxMmM2NWEwZTgifQ==',
                'remember_token' => 'l8Wh4podZhjCbwU6pnupLODFMcYeJ8XZw5al5cBgztkAmlebsJZgghHKuHyW',
                'created_at' => '2018-01-08 10:23:42',
                'updated_at' => '2018-01-08 10:23:42',
            ),
            30 => 
            array (
                'id' => 46,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'riz@codehub.id',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$J8MGdTYamZ2a4Di3WxfUNOOysUfEeT.ORMSnmzTafyOYo3kXs5dem',
                'verified' => 0,
                'email_token' => 'eyJpdiI6Imd5bGU0bnUzSUg5RWhaSkZQNGVnOUE9PSIsInZhbHVlIjoicFY3aXFwYzhsbHFjSnhZcFR2aXRFZVYzblNwRXNteFBhcXFaelNKdHRvTT0iLCJtYWMiOiI3ZDI1NmJiMjMxNWMzYzJhNjk0MGFmOWQ4ZGRkOTkyM2ZiNWQ2MTk0OWE5MDQ3NjQ0YzYyNDEyNDlhN2VlZGYyIn0=',
                'remember_token' => 'Dv0P1aSSGgUEgubVQzryqNapnXp9uRVLKlEVtgHJWxZAPzhpStRCf6FRlYim',
                'created_at' => '2018-01-08 10:25:05',
                'updated_at' => '2018-01-08 10:25:05',
            ),
            31 => 
            array (
                'id' => 47,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa22@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$8yQr5xGeoGTp429nphaSzOfI9KsuUVkoMTK5lYu1c6HFc4JYPh2Y.',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IkNRRmNMaUQ4RUFEa001TWlWTzNOY0E9PSIsInZhbHVlIjoielFxRTEzdEVGbnFCMzQyOGZmQmNVSkdCQUF3bXBYR2pRMXZXeW1Ja3pWaz0iLCJtYWMiOiIzOGJkNzBlZGM5NTAwOTBhODhiNzJmZWZiOWEyYjMwYzA1ZWJkNWY4ZTFhMDI5ZTNmMjQyYzI4MDc0MWQ5YTU0In0=',
                'remember_token' => 'WnWzgvzlbLedSCNpO0SeYHpAWEKNhNIu4tKln7JKCGlPkwsNxP3IRJqhpqeH',
                'created_at' => '2018-01-08 10:25:48',
                'updated_at' => '2018-01-08 10:25:48',
            ),
            32 => 
            array (
                'id' => 48,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa23@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$.UO8YwGe1JgRpRep9.ePZemVyvzztgrNc9nqrXTQdd0XTsfaCLgJS',
                'verified' => 0,
                'email_token' => 'eyJpdiI6ImsxcHQ1NVZ3QjRBdDQycWRrRmhRbmc9PSIsInZhbHVlIjoiSGI3STNmYVk2MlhFM1o0SFpiS3hRVEhkemJlOXNHNEZ4QUQ4R0FCUERFQT0iLCJtYWMiOiI1NWE5ZWUzNTIwYzBjOWY5NWI5ODczYmU1NzM4ZjdhOWJhMDhiNmNjYzhjYzRhZjA1ODhlOTM0NTQ2ZjEyY2FmIn0=',
                'remember_token' => '7kG6KKRvS4WBmwUvIUECCCh8tPuB48ayGhmLaLtJsNxLNFoKdB8Rahale7In',
                'created_at' => '2018-01-08 10:27:01',
                'updated_at' => '2018-01-08 10:27:01',
            ),
            33 => 
            array (
                'id' => 49,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'tes login gak',
                'email' => 'bisa24@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$2Umc6PQAUdctnNpHhG3kHuw529cDxtABimtN0PLwSMtZOw.8bpelS',
                'verified' => 0,
                'email_token' => 'eyJpdiI6InJtTkRscGtlUU0rOXczREV1cktpQmc9PSIsInZhbHVlIjoid1wvMURPMytZUVgrb1hcL3hsUDg5RXc3ZktTTjVlZkR0R3N0ZjBoaEhKQlM4PSIsIm1hYyI6IjRlZDVlNGUxMjNkZjYyZTRkMjY3MzUwZTM1OTdiZTQyNjU4NTQxZmE1ZjVjZmMzOWVhMjIyYjgxYzhlY2VlNDkifQ==',
                'remember_token' => NULL,
                'created_at' => '2018-01-08 10:36:35',
                'updated_at' => '2018-01-08 10:36:35',
            ),
            34 => 
            array (
                'id' => 50,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'bisa',
                'email' => 'bisa25@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$dVSR6V2VPGZLxkNfDBBPqO1RA184puhTi8Tk61eBHpXB.oAJCy1um',
                'verified' => 0,
                'email_token' => 'eyJpdiI6Im15UnA2V2lCYWR0SUc2dVpxU3o2N0E9PSIsInZhbHVlIjoiQjZTWThZVGRrMlN6Z01YSTJjM280QUgxWVNWZ3Bqb0hNQ0NLNzF0T3NqST0iLCJtYWMiOiIzMTU1ZjJkMzQ4ZTU5YTcwODRiMWFjOGJmNzE4NzRiZDg1NGY2YTE0NTNmMjMwODhmNzllYWNkZTIwZWIyOGQxIn0=',
                'remember_token' => NULL,
                'created_at' => '2018-01-08 10:37:14',
                'updated_at' => '2018-01-08 10:37:14',
            ),
            35 => 
            array (
                'id' => 51,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'bis',
                'email' => 'bisa26@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$xgcxhxtOTRwGqj5HbJ51PuiOtUzIcNFSYLtczBDjtssV/iwJ.QSEG',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IitiZGRDNzlNNldKME1wbUIxOUlHbGc9PSIsInZhbHVlIjoiSE1vRFwvSThMMTFjUXhjUExiaXJSYjFoWjBJSGZ4cnd4VjlmdURrSkxDV1E9IiwibWFjIjoiNWQzNDllM2Y3M2Y4NjAyYWY1MDMxYmMyNjIyYjU5ODc3MDExMDBkNTYzODlkYTQwNzAzZmIzNDgzYTgwNTYxMCJ9',
                'remember_token' => NULL,
                'created_at' => '2018-01-08 10:39:36',
                'updated_at' => '2018-01-08 10:39:36',
            ),
            36 => 
            array (
                'id' => 52,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'b',
                'email' => 'bisa27@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$x1FXSzE73zfAQQJ7tAl15u5/dkEB8p1tp/A.47u2C.I/4sBaje9LS',
                'verified' => 0,
                'email_token' => 'eyJpdiI6InVnczJNVmR5dUFKTFwvMk5Nd3RGeUV3PT0iLCJ2YWx1ZSI6IkVFOGNrZ1wvNUZTdDJLTWpFek4rZEc1a2gybVMxTGtob2ZneWJDU3c1QldFPSIsIm1hYyI6IjlkOTQ5M2M0Y2U4NTkwYzE4MGYyZGFiYWJlMmIxYjM3ODg1MzU0YTM2Y2FhYzc2Y2RiN2Q3MzI0NjU4MmE1ZDEifQ==',
                'remember_token' => NULL,
                'created_at' => '2018-01-08 10:40:08',
                'updated_at' => '2018-01-08 10:40:08',
            ),
            37 => 
            array (
                'id' => 53,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'b',
                'email' => 'bisa28@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$x/1PMIbeoS6/OkI8OfVn9eeGddiUYA1l2szURuuFlqabkIkDumQtq',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IlcybzNkTldrS2c5enI2ZXoxb3ZlNWc9PSIsInZhbHVlIjoicHBtNVUxMU9JbnpNTlNsTHFTOTU2RVV5bUFhM3pOOUMxbVJUQ1AyaHRKWT0iLCJtYWMiOiJmNjE0ZGEzZjI5YzFkMTFkMTZjMTE1NmE5NmQ2ODlhMGZlNDBjYjUzNzAxYmI3ZGZjMzkwZTc2YTlmOGE4OTliIn0=',
                'remember_token' => NULL,
                'created_at' => '2018-01-08 10:42:24',
                'updated_at' => '2018-01-08 10:42:24',
            ),
            38 => 
            array (
                'id' => 54,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'mmm',
                'email' => 'm@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$YpgqgvbMq1h5hxmkXacSyOQOEKfc.HtQ8fp0gL2B9aihWqqiGKDse',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IkpyQTdjWDFwb3NLenRHbTVtcjFDM2c9PSIsInZhbHVlIjoiTFgwMjVSaTlZN0VSWXhvYkZORnR5c3pRSTVWSDQyVjEyWlhhbHpoNXR2OD0iLCJtYWMiOiIxNWE4NDQ1N2MyNWM1OWMwMGFhYWM5MmZjNDgyZWRiMGIyOTA2M2M0MzQ0Nzg3OThiYWNjZGE5MzFmN2Q3MDhiIn0=',
                'remember_token' => NULL,
                'created_at' => '2018-01-08 10:48:38',
                'updated_at' => '2018-01-08 10:48:38',
            ),
            39 => 
            array (
                'id' => 55,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'bisasekarang',
                'email' => 'bisa30@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$9o.dfTgkMTu/nofw1.Nnvu/RtqBFNmXOrF5GJqL7tl2pmM4gtI17.',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IlJOYWc2V1JPdEVlT2VDXC9rK0o4VENnPT0iLCJ2YWx1ZSI6Ikh0V0M3VDhOaFFQT09vRzI4TnoyUXVwNDVJVEhzNnQxbjVkS2V6bzlDNUk9IiwibWFjIjoiZTFmNzlhNjhjNmY0ZGNlOTE4MjE3OTMxMzk5ZGFkNDM3ODFkNTc3ZDA1NjZhZjBhNmUwMWQ0YjBkNGZjMTlhMyJ9',
                'remember_token' => NULL,
                'created_at' => '2018-01-08 10:49:51',
                'updated_at' => '2018-01-08 10:49:51',
            ),
            40 => 
            array (
                'id' => 56,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa31@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$fMlexx.ZOpm91Bz20/k4AuKU8rpQggLWuYIYD40Dywpu9bZyoa4IO',
                'verified' => 0,
                'email_token' => 'eyJpdiI6ImFqMStrSFhrVzIySmJXK090b0VtWHc9PSIsInZhbHVlIjoiTU1TWEdVNm1DK1wvV1MxbUc5U2xNcllpZ1g1SDhmWEEwT1JRNW9hYXRUZW89IiwibWFjIjoiZmZkNTVkOWQyOGRhNzdjM2RjMTNjNDQxNDkzZWUzMmZkY2I0ZDNjMzRiZDE1Njg2MzZlYzZiZmFiYmNiNjQ2MSJ9',
                'remember_token' => 'WR8svHiThVmXxCZVE93wkFiDnxk1PveFz0G64TLnXkSp6HIjpW2lRP9h9OTY',
                'created_at' => '2018-01-08 10:50:26',
                'updated_at' => '2018-01-08 10:50:26',
            ),
            41 => 
            array (
                'id' => 57,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa32@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$PTov/yYBAz4M9D6ySeE2Y.zfXN7m5KvE/Psfh3qeOIwg7w8gDDfcS',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IkZSait3T2xndTRGQWVIcTNLZUdlSXc9PSIsInZhbHVlIjoiSFpTZWpjWnVxcEpWc3lacnh6YVlieEJ6UDR1Z05cL1RodWZpdGF0a3NnXC84PSIsIm1hYyI6ImU1M2NmYjI2Mzc3OGNiMjFjMGJkNDkzMWY2ZjhlYzQyNWEzMzk5NmNkODVmNTBlOGQyMTYwNTQ2ZWI3NzExNjgifQ==',
                'remember_token' => 'BfrEKzfb4R2PGzUKBuXMT87RCPYVK1nGeNR5pL0Z5OJdw90vzKS1m2tboTrl',
                'created_at' => '2018-01-08 10:51:36',
                'updated_at' => '2018-01-08 10:51:36',
            ),
            42 => 
            array (
                'id' => 58,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa33@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$RhEQ61dlWhW5GNd0TK7SP.Jo9WoUctHN7xmZNo7199wWi0E3tmTzC',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IldXaStZXC9NZVdlQjM3Vk5Xamd2dWxnPT0iLCJ2YWx1ZSI6IjdKNmtYWVNUWWlNS2xMZkpGMEVHemx5R3Z4VUNTR2pnZjNaaXhGelIxUXM9IiwibWFjIjoiNzM2Mjk4MDY2MjI1NjI3ZjViNzhmOGMzNzNmZjBkMThmMTE5Mzc3NGFjZDQwNmMyZjA1NGQ2M2M0Y2M2NTA5MSJ9',
                'remember_token' => '3qqFywKfu1hEmhB0Rjg8cMud1XGOZbyjG0Sas8sCQluqBEB2dhOCTstcQzZW',
                'created_at' => '2018-01-08 10:53:03',
                'updated_at' => '2018-01-08 10:53:03',
            ),
            43 => 
            array (
                'id' => 59,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa34@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$KPm32dqwbnQn6cWbZjc99.3Sxb7vaR1QzC/oAned1gY8ycPFGZheS',
                'verified' => 0,
                'email_token' => 'eyJpdiI6Ilk5MHUxcTF5akZmdHdLUnVMS0phQnc9PSIsInZhbHVlIjoiclZ4a2VpeFgwVGFUUEoxNk5hclpKNWNtWjcySGRVOWpaRlV5ZUJ0bFVxVT0iLCJtYWMiOiI4NGJjNzMxNDQ1Yjk0ZTkyNTQzYmM0Yzk5NjgxMTBkMDMyNjg2ZjBjOGQyNTJjYWI4OTIyN2ZkNWY4NjcwYTJmIn0=',
                'remember_token' => 'KcDomyHzglmeLvPRWQZO0kWC0OTRUj4YIUqB7R8qcoCeZItfMK7trmNfoQSg',
                'created_at' => '2018-01-08 10:53:45',
                'updated_at' => '2018-01-08 10:53:45',
            ),
            44 => 
            array (
                'id' => 60,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa35@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$qXSin8kHc9mxtXFYL1NxgOP2aZCZna0GbB2V700TQeY5dfWuNOOrq',
                'verified' => 0,
                'email_token' => 'eyJpdiI6InFSU1FjSXdXXC8xUnJPeXBpdVVMUGR3PT0iLCJ2YWx1ZSI6ImdFZ3JvelNYQzZSeUp4ZDBDODFuS1NcLzNkK29XNXpNR3BuSnErMHZhMG9zPSIsIm1hYyI6ImM2NThjOTg1OTdjZWY2ZWFkNTk5NzYxODk1NjBlNDJhY2YwMDUwMDViMjE0NTFhZWU0MTdhMTQ1MGUwNmQ5MzMifQ==',
                'remember_token' => 'W5l397savmFNaggpXOyZZVHzdDZxSkkZ63nhxlfrWDTyKwJElGqL2oofXON0',
                'created_at' => '2018-01-08 10:55:40',
                'updated_at' => '2018-01-08 10:55:40',
            ),
            45 => 
            array (
                'id' => 61,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa36@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$ilYLeAs5HHz/uXFZHPrWDOw5OBu/7tIpoAPu17/1Ug/LHtrxmXHZe',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IjZiNlwvUGtyXC9QeUhieDhiNXlZemNDdz09IiwidmFsdWUiOiJ0Z0hTUmZMT3I2MjFoUGxXelJXQTJhOXlFWlVXbTVCYTg5NDREMWo1WnpZPSIsIm1hYyI6ImI1YzQzMDcyYTUxYmRlMjdhNzFlYWQ0NjM5NzFlZDRiNDgyOWQwODQ0NzkxZjhhNzA0ZjdhZTI1YWRkMjk4ZDAifQ==',
                'remember_token' => 'z0AtoIkAmBKAjNyNwoInGOZ4CUPuLbpStg7bU59olNrNOFegTMP3Y3IaVnND',
                'created_at' => '2018-01-08 10:56:40',
                'updated_at' => '2018-01-08 10:56:40',
            ),
            46 => 
            array (
                'id' => 62,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa39@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$JhFy4A/QDC6ZNpteEogpAO4hSVL7zP2Aik2g1VKoCvTZhzIO5iOzq',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IllYOThuSzhrcVhGUm1lWlhXNHJhWEE9PSIsInZhbHVlIjoiSnNFSTlEbHBhS3JYdXpraElibnpMQWxORHAxR240WjIrMUNpcDdyTGptOD0iLCJtYWMiOiJiNzdiMjk5MjA1OTkzM2Y0OTk0ZTM2MjEyMTc5ODM3Mzk4OTFmNmMxYjc0NzI1NmI2MTYzNTNjNTI2NTgzMGEzIn0=',
                'remember_token' => '2kRSDPXyBdhEOs3fKOfMY8D9tcOzKqzrXoaFMNhbkJwvpsWtkPTjfIvpHdbv',
                'created_at' => '2018-01-08 11:05:25',
                'updated_at' => '2018-01-08 11:05:25',
            ),
            47 => 
            array (
                'id' => 63,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa40@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$1vxv4jPMh879ag/T7xiuRuC5pLv3/lxoGVqHv2dmpP5/Xi99dD0Mu',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IkhvWlFhcWh4YlVjM21td1ZoVlZxSkE9PSIsInZhbHVlIjoiWThQT0RMOUNoSGlKanlEcnNqakM0TDRGbWttNjZMc0pkRnFHMlRJR2h2WT0iLCJtYWMiOiI4NGQ2OWM5ZjZkZGQyMjA1MmNhNDM5OTQzZjJlMzQ1NGZiYTJjODMzZGU5Mjc5ZGFjMmIxMmE3YzM2Y2YwZGUyIn0=',
                'remember_token' => 'mjm7AsDpxNalzBFfCweqC2EvvOhoBstrihLBRsNo1jqBTh23IY5X1RdJR1WK',
                'created_at' => '2018-01-08 11:08:54',
                'updated_at' => '2018-01-08 11:08:54',
            ),
            48 => 
            array (
                'id' => 64,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa41@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$A3T0YX6okj4GL9c8mRYKqeqz2QBTQRYh517XYTv56T.2IKz.DP.m2',
                'verified' => 0,
                'email_token' => 'eyJpdiI6InJYR0lISzgxc3NSUml3SndldjhvRVE9PSIsInZhbHVlIjoidG51c0xrVmlYU0picGErUTBnaXNQNVRDMk9JUjA5UVpoVHlIUGJHT0RYVT0iLCJtYWMiOiJhNjgxNzNkMGY2NTI1ZGQ4ZWNmMTkwNWNmYzk3ZGZmOWJkZWIzZWYwYmJjMDdkMGFjYWVjNGMzZmY5NzE5ZDk2In0=',
                'remember_token' => 'z5LIk8pW2oWi3pze3iCbrCGXhh4kwIsG4lGqN2WDQqb5jqMNh4eZBfEtNUcQ',
                'created_at' => '2018-01-08 11:13:40',
                'updated_at' => '2018-01-08 11:13:40',
            ),
            49 => 
            array (
                'id' => 65,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa42@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$/Z4WivK9fOjb7dk55RxlN.Dg/IqqqfLZdrUuGhKvAphuYM0F2ZgAq',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IjYrY2RFcFwvS0hCR2VwR09EaUcrRGpBPT0iLCJ2YWx1ZSI6IjBqd1pcLzlHUDAwaklhVmExRGxJaUNud3J5R3dUeVpiOVZZdlQ1YmNUYkJnPSIsIm1hYyI6ImNhZWZmZjVjNDAwMTUzNjQ5YTA3OWIzYTI1MmVhNzM0ZDUzMzIyNWMyMmZkNjg0NzVjMTA1Y2I0OTg4NTQyNDUifQ==',
                'remember_token' => 'ImV5RjMuk3feAy4bTixIWxbAFmFgE7ZFmrL8QqrruNVi6q0pHju5jzilRSIv',
                'created_at' => '2018-01-08 11:17:44',
                'updated_at' => '2018-01-08 11:17:44',
            ),
            50 => 
            array (
                'id' => 66,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa43@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$cPTbkVLrfHH54vPfoXcNMOzOAj6BCys.q5YuHEBwgoLgnngv5CiG6',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IjZRdkJ0bWNXVHFZVVVlTEx0QkFEdWc9PSIsInZhbHVlIjoiOUVHTzRicXhsWWxGSjh1b2t0TXZ4UkhhcURGQTh5N05adEdnRmRIUGJzcz0iLCJtYWMiOiIxMzQ2MmEyMTk5NzUwNjRmNDVlNWY5ZmZkMWY3NmJjODdjZGUxNDU5ZTI5MjhmOGRmNDdlNjE0MWRjMjNiZDgwIn0=',
                'remember_token' => '3Ew6RTYn8SBRThLH6W3G8digoOMQuEH0gPBOUWlw4HzPHliI0AamY18W6h5f',
                'created_at' => '2018-01-08 11:18:38',
                'updated_at' => '2018-01-08 11:18:38',
            ),
            51 => 
            array (
                'id' => 67,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa44@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$Cn6FbdA95f4vlhsAB0MYnOgay6d.PuQR/Bu/dVGDtcB/nbY6FxNry',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IjRDZzBGTm11bDNGaVRaYXBLdXZLaWc9PSIsInZhbHVlIjoiUkFlXC9majZ5RndvNWhHQks5am1FYTRsdjdmK3dsb3p3NW5WZXhuY0o2QUE9IiwibWFjIjoiOWI2MzgyNGIyOTU3ZTQ5MDFmYjE4YWZjZTQxYzc3NzA1MTdmYTY2N2JiODI4M2RmZjk1MDk3NTY0ZTBhZjNkZiJ9',
                'remember_token' => 'SELuroMjYdJYKNKLZ2yZKoJyd923CuMzF3GI4Qd2od0JJpE4b79z0MReFmZf',
                'created_at' => '2018-01-08 11:19:18',
                'updated_at' => '2018-01-08 11:19:18',
            ),
            52 => 
            array (
                'id' => 68,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa45@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$GxswXeue8Z6sNREPdypMMuPXcK7NG7WVocmxeblCV2JfRQB7wrupC',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IjFiWkJhVFlDblJ1T2plbEh0QnZIcUE9PSIsInZhbHVlIjoiMjFzVHFsSVhTaTVTY3FBbVdNNFl0UlZhQ3hnMlNjSk9saklMNWRFYjBXVT0iLCJtYWMiOiIzZGFjZWM4ZDMzMmRkYWE4ZTBjZWUzMDhiZGFhZWIwMGJhOWU4YTk5MWU0ZDc3NzVjNTcxN2NiMmM1YmI1YTQ4In0=',
                'remember_token' => 'TA7ft4uhBqxIQ3U8LVD8nNmSM7OLccQLO1jj60KMD4tOPEQzapVNJ3V3MVhy',
                'created_at' => '2018-01-08 11:20:10',
                'updated_at' => '2018-01-08 11:20:10',
            ),
            53 => 
            array (
                'id' => 69,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa46@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$Fqu06gP65EBjecc8he7oEuniHBH/C8Tvo.LwIdUA9cTcXt1S11RL6',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IlRkMXFHWVJVYytjaVc5czdZNGVSVFE9PSIsInZhbHVlIjoia0taNkpPSDlmRlpcL0dCQ25Md3E4UWFcLzh5Y0lOTm15UmQxU0JieEs0TCtBPSIsIm1hYyI6IjUyMTRmMDU5NTMyZjMwMTY1N2NjZTkyMDFlZWU0OGZhYzI2Y2Y2OTY3ZTAyNjYwNmUyYWQyZDVkMDUxZDJkZDQifQ==',
                'remember_token' => 'Wt5AFuzJsvPJuCe4YbYX58esqmOP7WVR0Hloyo0EHsu1iPdDMH3jsbS9WTLr',
                'created_at' => '2018-01-08 11:23:05',
                'updated_at' => '2018-01-08 11:23:05',
            ),
            54 => 
            array (
                'id' => 70,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa47@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$ECdoR0WWgj6JE1ZyR59.0.H.xYWm0pZVGzSxadpra./v8a1maxehu',
                'verified' => 0,
                'email_token' => 'eyJpdiI6ImVsOWZPQmJkc3NhdmVyQ2NVa0R1QkE9PSIsInZhbHVlIjoiR2NQMlNscTdiQ1BMMXpBMk9WdmNZcGt5K3VnZlRaM3J2Zm9NSG8zWHF6az0iLCJtYWMiOiJhOTBmOTNiZDViYTc1MWI1MTRjNmU5MjJjMWYwYmRhZmE4ZDg1MDJkY2E1ZjdhMTJiMjM2MGU4ODM3NzQzYmM5In0=',
                'remember_token' => 'hLnz99Rq9zD3RaLxmmtY6EWFV20Sop0yYrbWe0gYD7mPd4Mg5zYgSOQ4QayY',
                'created_at' => '2018-01-08 11:24:17',
                'updated_at' => '2018-01-08 11:24:17',
            ),
            55 => 
            array (
                'id' => 71,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa48@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$ylkFkmvbQ.NxMHR5NyvqjeJifCmkhIPNxYSvPOmF/xGDVaUCoc/Ne',
                'verified' => 0,
                'email_token' => 'eyJpdiI6InlzZFlsUUJCTlVjT0cwY0hmVmdIQ2c9PSIsInZhbHVlIjoiWXB3ZFh2WW1aZFhMM2xqTk5zR3E3eWxcL29NcmtQenNcL0dYOURhS0lEVHRrPSIsIm1hYyI6ImQ3MDk2NWUxZDdlOWY3OGYwNDBhNTNlZGFkZDAyZDIyMTA2ZTE2ZTkxYmNkMTNjMDgwNmUwNjk3NTVlOWUzODQifQ==',
                'remember_token' => 'DX5rqrB1e4As29sO3xrAyJcqOMFS1eoGkumUNbAWUFebdxoZeAFQJwx4bhXc',
                'created_at' => '2018-01-08 11:26:02',
                'updated_at' => '2018-01-08 11:26:02',
            ),
            56 => 
            array (
                'id' => 72,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa49@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$oTWykWgVIDvo4uxKzURvR.LIo2fYkuWLTXt/pWpt6BcDuNHFeeqXK',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IkZKMmJteG1HZWs3N1VvTWZFVDJWWkE9PSIsInZhbHVlIjoiXC9SZndOUURsclI4K2Q4RVl3WkRoQUtBenJaNEgyUnV2bHNXajBoQ1FRV1k9IiwibWFjIjoiOGM1OThjZjMyMjg4NzE2YmUyM2ViYTkzYzk2ZDkyOWYzMjk3ZDNkODNmYjhhMDFhZTlkNzM4NzNhOGU5MjFjOCJ9',
                'remember_token' => 'HSzp8iCrvOBXNcric2Xc4vt4oouyK4pZE04Gzup5JdpezowqGqhJ3RHpRf32',
                'created_at' => '2018-01-08 11:28:42',
                'updated_at' => '2018-01-08 11:28:42',
            ),
            57 => 
            array (
                'id' => 73,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa50@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$hvTItszt6qQSX9Mk8TEg1ej7TpE29hBeRXd2hSjVZMvZclfDlW2Ly',
                'verified' => 0,
                'email_token' => 'eyJpdiI6InBRZUVCNDB3ZlpVYThRUWh0b2M2SWc9PSIsInZhbHVlIjoic25mT3pydG56bGVQVlNldTFHdjJQWjh4RUV6TmJcL2FHWURYdGZ4YjJ5aDg9IiwibWFjIjoiMmI0Zjk5NmM4YWJjNDBlMzU0OGEzOTMzMDUzNzk4YzljYjIzYmY2YTkxODU1YmZhYWU1ODNmZTNjZDJmNjUyNyJ9',
                'remember_token' => 'ctEn8dfXYmoOfTtzts544lJeZLZh53WJIbvOh0bTushhaOCufBQKHrZ3r1LZ',
                'created_at' => '2018-01-08 11:32:26',
                'updated_at' => '2018-01-08 11:32:26',
            ),
            58 => 
            array (
                'id' => 74,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa51@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$FumEZ5xQ25niW0Y1xGiRxuLrZZWlubRF081blMBHuxdtrBmoTMGdK',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IldkSUVFWGU3aE1TM1l2dUY4Mm5wWkE9PSIsInZhbHVlIjoiWXJtQjVxRVVaT3ViY1dJQ3BhYituK1pPcFNyenNcL1NNU2wzZDU1RktKZTQ9IiwibWFjIjoiMjZjNzQwOWMzMzdhMDgzMDQ1MzJjNGU5MGY5ODBlZmJjZjhjYTkxMWRkYjllYmZlZTFiMTc5YTJkOTJiNmJlNCJ9',
                'remember_token' => 'NI0WAwc3cnluyxBoOK7DaPWxq3cAo9MzPmTEiTAFTBShucSNRKN8iBrR1VaY',
                'created_at' => '2018-01-08 11:35:56',
                'updated_at' => '2018-01-08 11:35:56',
            ),
            59 => 
            array (
                'id' => 75,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa52@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$K8ph3NYby/yaXmdQVHbu6ekarxjlS9Zn3Vw2H6S.8C0lv/Y8HvR36',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IkdadWc2OWlMZUNlZ1wvR1ozRE84aVdnPT0iLCJ2YWx1ZSI6InQyZjE3SGl6bEFuUVd4bEZjWmU2TzhsZ0hjd0ZqYXFINWY2d0JCVUd0WGs9IiwibWFjIjoiNjlhOGNmMzg0NDE5YjUwZTMzOWQ0MDU3ZmNhYTFhYTJmMTU0MGIzMWZlYWFmZjAxYzJlMTk1Nzc4NjQzMGUzYiJ9',
                'remember_token' => 'jaYG2kVXwm7EejSoMK8g3jm5ihPhvFcepZG3Hptrvf9QuzAxX0ESU24XVYFc',
                'created_at' => '2018-01-08 11:36:54',
                'updated_at' => '2018-01-08 11:36:54',
            ),
            60 => 
            array (
                'id' => 76,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa53@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$da9/RmJ7uMvB2kCiuXE5wO.jw1ty8rs48H354pIZ7KIv9hd1TzI1i',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IlhXK3lyQ0plTm1MdjhkdEhqQ29iZlE9PSIsInZhbHVlIjoiUzA0WkRPZ2IrWWM0cnhJaDA5aUJWa1VHTUtaVXZPUVh3TEVLQmR0OHJSWT0iLCJtYWMiOiIzMWVjOGI1ZTFlYTczMjM1YzMwYTE5ZTNmZmM3ZmQ1NzNhNzRiYWYzOWZjYzIxYTU0Yzg5M2Y4ZGU0MWE1MzFiIn0=',
                'remember_token' => 'LNGEy8FYfYJfqLVyCtYq5INgvVq5pIPkui1bBIi3cFFtaz5nX869ABalXPDc',
                'created_at' => '2018-01-08 11:38:05',
                'updated_at' => '2018-01-08 11:38:05',
            ),
            61 => 
            array (
                'id' => 77,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa54@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$.2D/bTFdtkvgokPbTYSWkeWUhu7vi7sF/TZi7A1QD2YAfM2hJXK2u',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IlJjYThpTSswTXhcL3l5aWpweE5jZmZ3PT0iLCJ2YWx1ZSI6InZYVzlRbEtLMkIzQnNjMVFGT09sXC9FbkpZWDVDanYxbUxBOXR0eUZDTHVRPSIsIm1hYyI6IjRhZGRjMjNkNDBiMjc2NmM4ZDc0ZDcwYTcxNTk5OGRkZGE2M2EyMjgwZTdjYzhjYjhiZWQ0ODUyZTdlYzkwNGEifQ==',
                'remember_token' => 'Jh44thonMcwyQX3u8jmGCJXEQgj4GlyeQgBynarBKi0uwdONvtO8nvulpZVT',
                'created_at' => '2018-01-08 11:40:02',
                'updated_at' => '2018-01-08 11:40:02',
            ),
            62 => 
            array (
                'id' => 78,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa56@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$hyfM5scoMF9CPHizQC2vU.5wYIXl3k5Z5xdpUl.bRzpvUkTUc4kz.',
                'verified' => 0,
                'email_token' => 'eyJpdiI6Inc3ajNxUHBXWDJaVnF3SDJPWlVJWEE9PSIsInZhbHVlIjoiWHF6NEVBb0NGS2VwXC9sbjJRMWprUmhSN1ZkbEpCXC9XQlBQbkdwemIrdk5ZPSIsIm1hYyI6IjE4OTYzMGVlN2U0ZWE5N2FiYWQzY2NhY2QxYjFhZjhlNzUzNzJlYjNkMzlkMTZmYjc0NzdkZTQ2ZmE2MDIxNTIifQ==',
                'remember_token' => 'G374KNtJpgmWVT2mKC7yGn152tf6GHiBWixMoeKHRaTaTNytcPkbN6o6s7RI',
                'created_at' => '2018-01-08 11:41:18',
                'updated_at' => '2018-01-08 11:41:18',
            ),
            63 => 
            array (
                'id' => 79,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa58@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$AvVLhFmlRYxz2NmOwQQwtOjfjAzJecLl3XHQVlX0Ek0qVq53zNI26',
                'verified' => 0,
                'email_token' => 'eyJpdiI6Imx4VEVDWFA2NW5jS0thM1c3Q2s3Vmc9PSIsInZhbHVlIjoiMUZ4NUJZa1Q3UGFxVHFBTVo0VzBqczgwbEpJMmpcL0tiR2lLb0lCeUMwT0U9IiwibWFjIjoiMzQ1NjBlZjViYTgzZmQ1NTEyOGY1MDA1ZGQ0MDE2MjQzNWZjMTQ5NGM5ZjJjZWVjNjNhYzY5NGFkMWE4MWFmNyJ9',
                'remember_token' => 'NHP16lGs4TOo6z5ASQ3tbrH64PlKlyL4TDT7Xqo3dJsKLHTKKtuSjDKkk5O5',
                'created_at' => '2018-01-08 11:46:08',
                'updated_at' => '2018-01-08 11:46:08',
            ),
            64 => 
            array (
                'id' => 80,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa60@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$Z72BRVy5tEyc1V8B3oMRx.ePujVDAbzfyDpEEtv7dAATWnVkcNOW.',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IkNmSnF5OG9jcmdYTjlTS21GTk85UUE9PSIsInZhbHVlIjoicTNsMmlwU2pURTV1K0QyMFcraDVvam1qcjdZcUtoWlhsUFY2cVpwNDQ0TT0iLCJtYWMiOiIwNzdmMjlhMDNmOTZiNDM4NTU4Y2QwODA4MzA1MjU2MzdkZDMzNzExMzU3OTFiOGU0N2ZlNTYwYmQwMTY2OGVjIn0=',
                'remember_token' => 'keMHpGPhkljpJveGewT2aFLH2kDb1z7LbtjG7DG2ryNG7VHs9WKV4YTgGr0q',
                'created_at' => '2018-01-08 11:51:08',
                'updated_at' => '2018-01-08 11:51:08',
            ),
            65 => 
            array (
                'id' => 81,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa61@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$qtriiufrZXO50GOzQLDMH.AMLEfYr0FktK0qkMLTPhT..o02kG/yq',
                'verified' => 0,
                'email_token' => 'eyJpdiI6Ik56cjJcL1wvWlQ0UFhJU05SYWJ5S0JUdz09IiwidmFsdWUiOiJSTGtJaXYrakR0WDlZd3hldjFLenNxMFJOYXBMY29nckoyZnFxWTQ5OUNzPSIsIm1hYyI6Ijk2ZWM0YmJkZWQ1YTlkOGJiYzRjNzAxNDBiNWQ0MmRhOWQwMGQ4YWYzNzg4MTU0OTk2ODZjNWIwODMyNzAyNmEifQ==',
                'remember_token' => 'jrIslsAe3YXMXf4oQM8jAq12dwbI4MtHX8MkNuJ6V9itS9uMCxxl1HQ4CF8w',
                'created_at' => '2018-01-08 11:51:53',
                'updated_at' => '2018-01-08 11:51:53',
            ),
            66 => 
            array (
                'id' => 82,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa62@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$KB/73sXnjFi8Zqxy3sCmnOcS/3wS1J94vY4Odexc.fBfHCu711Z1m',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IjhidDY2YVEza3g2NDR6OTJHMVwveW1BPT0iLCJ2YWx1ZSI6IlA1cjJBMXEwaUlicWhnbVlUUVViM1dyV3k2bmw0aEhhRkFyelZiUldTXC84PSIsIm1hYyI6IjVhYjFjYmZlZDVhYzY4Mzk3OWY2ZmVhYjQ3NWU3MGE2YWI5MTEwMzUwYjRkYTgzMTJjYWQ5M2I5NTdmOWI3ZjUifQ==',
                'remember_token' => 'P7xq07uuCVRPG34ADZx284ppMEEJ3vFI9jX8gDvCMbQ65kYQkIpFEWRbu7q3',
                'created_at' => '2018-01-08 11:52:49',
                'updated_at' => '2018-01-08 11:52:49',
            ),
            67 => 
            array (
                'id' => 83,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa63@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$8WjPNUxu5jrYVmNABJEiUuf9mB37T1tyGNesRT8KSmNqO8V1mhjNi',
                'verified' => 0,
                'email_token' => 'eyJpdiI6Ik1QYnExZ0FWYnNWbnRhRHEzWHNYT2c9PSIsInZhbHVlIjoidjV2aXY3eUp5NTYxZUVJYUxaeXJuenRhcngzcVwvUU1PeUJzWGxvS1RwU1k9IiwibWFjIjoiYTViOTdiZGNiZjhhOTEyMWYyMGNiM2IzMzRiNmE5NjUzYzZhODI4YWY5OGY3MTM2MzhlZjQ1MDU3MmNkZDU3ZiJ9',
                'remember_token' => 'pCRxaVNQqxaaf7fLIlNxZ4n39z10XPjXmRCQ4fmLO6T8Z91SexobkAM2PbJb',
                'created_at' => '2018-01-08 11:55:28',
                'updated_at' => '2018-01-08 11:55:28',
            ),
            68 => 
            array (
                'id' => 84,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa64@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$mMaGjBmnNlmCXS5XcCKTZObr44SSzBK4sh17TdmSEjFSc2RweEb4i',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IjU4Z0c5ZkoxbTNON1hcL1FsMTBoczh3PT0iLCJ2YWx1ZSI6IjcwdkY3YlNlQVczQk4wRnJkRXIyMWZlbng4WjN0WnJ4OHVnMnhDTGNjVXc9IiwibWFjIjoiY2RjMmNjNzU3MmMzYzRkMzQ0NTNhMmJjM2UxMjIyOTE5YWNhYTk4NGZlNGYyMzI3YmM5YWRjMzJjY2NiYzE3NyJ9',
                'remember_token' => 'LAQvZVvpYzfRmS1TqTNq7kdWA19t97hnGpPv7vBVJbEDoW0fMbpXhzfWPebC',
                'created_at' => '2018-01-08 12:04:41',
                'updated_at' => '2018-01-08 12:04:41',
            ),
            69 => 
            array (
                'id' => 85,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa65@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$ytx1JF2c3xXBrAoLgi1QruGhDZsg6W4DRDYI.cvAE3OHPseEq7/t2',
                'verified' => 0,
                'email_token' => 'eyJpdiI6InF2RlpKdTY4emZYZFBTcEE3NXBqYlE9PSIsInZhbHVlIjoiYUZoK1UrNVwvNW5DengrVzczXC80UUNMOU4yWlBWMUptd2s1Z3EwS3lDazhnPSIsIm1hYyI6IjgyNWI5NDhkZDQ4MjQ2OGZlYzg4N2ExNDY3MjkwMjE4NzRmNGY1YWNmZmRlZDQyMjBjMDBkZjc5MzMwOTc0NzMifQ==',
                'remember_token' => 'MXuQJ1w4FF9XLqCDFz59JHtPoAs7ZV1Va2b9E0fiZQGbkz0nklvUuxApqtMc',
                'created_at' => '2018-01-08 12:06:04',
                'updated_at' => '2018-01-08 12:06:04',
            ),
            70 => 
            array (
                'id' => 86,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa69@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$qzqWNG24J/QOZPR.PvJRK.mfaSMawJur4rInzbCRuu9f4muwZcipu',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IjBVN0czMld3VXk5MHVLOFdUSDZQakE9PSIsInZhbHVlIjoidSt5dk9DaUZyMDZNZUU5V2pRVko4SDNIeFd4SGJHYml0UWdCNmtSY3FvQT0iLCJtYWMiOiJkOGU4MTJlMWRmOWZlNmU3ZmY0NTBkZDFhY2MyMTkwYTU3YjA3NzYxYzkwYWRmZDkyMGIyYmFiNDcxYTg0ZjJmIn0=',
                'remember_token' => 'ULHdLsPsXdA57bqnXHbBOuOOFqemvYohouJWBTiDtGKLnqGnEI2itvvTfLy7',
                'created_at' => '2018-01-08 12:36:39',
                'updated_at' => '2018-01-08 12:36:39',
            ),
            71 => 
            array (
                'id' => 87,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa70@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$q9eU2/ut79QuDIroJSBwk.CpsrjmdFDpZGL2EltQhSLyMlYQ.LwRe',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IllYdDZhN1JPQWpxQ3ZXSjBaUkJ4QWc9PSIsInZhbHVlIjoiam1ZTUl6azFKRVB0NDQzSnFcLzFoV0x2WGxvcGlvbURvNVwvWVIrK2FiNjkwPSIsIm1hYyI6IjBjZTlmZThiODVkMmU1ZDczOTc2YWZlYjk5ZDNhMGY3YjQ1YWMwODcxYmU0NGM0ZGRlM2NmNTkwMmFkMzM3OGEifQ==',
                'remember_token' => '2UfgdveeiBfShIq8plI9PCk0WXsGiHV4A6cDnqKIVPlnUFp58LNMjcM0mbw3',
                'created_at' => '2018-01-08 12:37:33',
                'updated_at' => '2018-01-08 12:37:33',
            ),
            72 => 
            array (
                'id' => 88,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa71@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$jxu.wREKNZclM9e3BG5SSegnhP/jAwys6Co8yY4EcJOGepC8B4fwa',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IitFTGZzOWpJeU1HUUF3dEhKaUk1aEE9PSIsInZhbHVlIjoiR3NkRTNSQ2R0ejY0V1ZlcWFSN0JRR3MwTkoxeFFMTVY1UkN5QnpmZDBrWT0iLCJtYWMiOiI2NTQxYjRjNzljODM3NWE0YTIzYzIxYTM4MWU1OTVjMDY4MGU2NDFkOGUwMjFhYzVhMjQ0MDczNDIxNzZlYTc0In0=',
                'remember_token' => '9TtAc9XA1JVSebpHz5kUe0jFbs1OxZ5wq1WBAHNv6Epo1BxeHnZeNld4fZq9',
                'created_at' => '2018-01-08 12:39:05',
                'updated_at' => '2018-01-08 12:39:05',
            ),
            73 => 
            array (
                'id' => 89,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa73@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$N1gFjimBtXntCXyjClCtg.EwiWE1YvE8rB.jF0gR7ggK.VVnIjmIO',
                'verified' => 0,
                'email_token' => 'eyJpdiI6InF0K1o2MFdGSkFzREFUd0FzM1ZHeXc9PSIsInZhbHVlIjoibkxLdG5vV1JwTnhTbnIxdUs0bENyMFpoRTFISnd4VGcrSDNjRXlNUWs0cz0iLCJtYWMiOiI3N2NmMzM4ZjI4Y2YzZmRjM2NkMTIzMDRiNDVlMjhjOWYzNmJlMzViYzdhNTdjYWRjNjJmZTY4ZjBmOGRlOTNhIn0=',
                'remember_token' => NULL,
                'created_at' => '2018-01-08 12:45:25',
                'updated_at' => '2018-01-08 12:45:25',
            ),
            74 => 
            array (
                'id' => 90,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa74@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$lHW5lsYFenp7rtezZS1BnOgBXPmaUbzXAexRi3otUpuVXwW2B8Ypy',
                'verified' => 0,
                'email_token' => 'eyJpdiI6Ik5oZlRGeDBTUWo1THcySnVkREYzclE9PSIsInZhbHVlIjoiV3VZRkZmcUNFaUxZMStKOE56VTFKbTFaaTNodXNVdTVMc1wvQjBMNHg3Zkk9IiwibWFjIjoiYTFiMTc0ZmNlNTBhMzIzNWNlNDMyYWJhMGY3ZGUzYjMzZjBiOWQ5YWJiODczY2U2OTQwZDAxM2U3MTgxMzMxOCJ9',
                'remember_token' => '9h8yOsDWrkVbx8XAxmYiHvvdp7DrKaPokaxhsYspY852C1tI4QB6WFzDUBlJ',
                'created_at' => '2018-01-08 12:46:29',
                'updated_at' => '2018-01-08 12:46:29',
            ),
            75 => 
            array (
                'id' => 91,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa76@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$ND94ZxSGwJhYVALa15ayJukhQr4B4OBPew0WnxivIiRJSGsLJNHPK',
                'verified' => 0,
                'email_token' => 'eyJpdiI6Ik51ZkpZcTJkSHlxMzc1eXFjNUhGZ2c9PSIsInZhbHVlIjoiaWlhOE9JSnBBY0I0ZXVDRUJjclMrSmVXSGRGRlNMcGphMk5aZWFNQUJZQT0iLCJtYWMiOiJhOGJlZjI3MWFkNzljNzQ2ZGZiNDRlZTU4NTgyNWY3ZGMxMDI1ZjViODlmNTlhZDg4MTVjYTU0ZjA4MGE5ZWFlIn0=',
                'remember_token' => 'wUupA7nk0DNp82PssBNiZNMjXcSFKT9xQNAMjyLIuC1QZ5xY1LGD61Odpqfj',
                'created_at' => '2018-01-08 12:49:14',
                'updated_at' => '2018-01-08 12:49:14',
            ),
            76 => 
            array (
                'id' => 92,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa77@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$6XxxeI38H9hMXAelQmdE4uxjPriti1nuobGNe18UOKTEtpGbDeqm6',
                'verified' => 0,
                'email_token' => 'eyJpdiI6Ik1tcDBOTWpGdUdOZWJTanBYREdnU2c9PSIsInZhbHVlIjoiVnZ4MHJNQXkzSmZUTzhQSHBcLzhieEZaMG9KbnhqUCs0amZGUFhTN3UyVTQ9IiwibWFjIjoiY2JiMzg3NTYxYzFmMDAzMjFhMmRlMmNhM2IzNjZkZmFjYTdhOGE4M2EwZDZiZGJjZTJjODQ2NWY2YjVmODE0YiJ9',
                'remember_token' => '1XUuTW7auGsrlnbENbzFe3ylurGnJE8xdmeIoo8zJL49yGWUuiBV1BGCvLcH',
                'created_at' => '2018-01-08 12:49:56',
                'updated_at' => '2018-01-08 12:49:56',
            ),
            77 => 
            array (
                'id' => 93,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa79@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$bIDTFXRWgBvn1OFs85IQtuwCs1RKiaAPePoF/wRbeS6U5l4q0FQba',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IjRaQm51c0VmTHlmaTVIYUFhclBBRnc9PSIsInZhbHVlIjoiSFhUeXkzck1IMktsNW9TUTBjdzVUVGlodW1tV2ZVZ1JZaDlvOWp4Ujd2dz0iLCJtYWMiOiI0NDg2YTk5ZGQ0MWJkZTgyNzM3NmY0NmVkODczYzZhNTJiNzc0YzAzNzhmMGNkMWJmMWQ5Y2E3MzE3MzQxMGZkIn0=',
                'remember_token' => 'wgk3H1wF5rHXGDoxuKjSLtuHSFaz7QXCl2EQiLfLWoWhsl7bFxNtgnT0HeoO',
                'created_at' => '2018-01-08 12:51:05',
                'updated_at' => '2018-01-08 12:51:05',
            ),
            78 => 
            array (
                'id' => 94,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'udahbisa@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$E.2pgG5qo4l1K3sH8qHFR.BdGEUMj3us.3zQj/JohMjNzis26CYL2',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IlwvckpBK2VBTHpVVzJkWERlYUQrMyt3PT0iLCJ2YWx1ZSI6Ijk3NDNSSE1PYTl3azh0dEFPWnJRM1FtcFg2TmFCVGw1M3N3d0VcL0hZbVU4PSIsIm1hYyI6IjQ0NGQyMGRlMGI3NTRkMzY0MzU5MzlhNGNjODIwNzJlNjE3YzQ1MzQxYmNkYmViOGQwNzQ3ZjYwNjM4ZTJiM2QifQ==',
                'remember_token' => '7N60fZVzJnUemYXwCuSRbs3HRM6Ey5EUtAI3cqBoC5bqGmr2QH8FEXng8EF6',
                'created_at' => '2018-01-08 13:01:21',
                'updated_at' => '2018-01-08 13:01:21',
            ),
            79 => 
            array (
                'id' => 95,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'udahbisa2@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$Q2VNul/WiWI3XDNd1BZTXORp/m6Cn6hTYmqEQ/O6sAcgBaZJyaAp.',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IitSejQ2cWlzd1k3MjBJUVhBaWFrZVE9PSIsInZhbHVlIjoiT0xIblVROGgzNDBMdlRmd1ZHM0pJdjI3eE9OMDlleXhZUk9QV0hoMU5nST0iLCJtYWMiOiJhYWE5MmFjYWJkNTMwYzQ3NDE3ZTk1ZWFhMTBhMzczNTkyYjIyNjcxNWE1YjE3ZjJhNDhlYjVkNzNjNjM4MjE1In0=',
                'remember_token' => 'w2LkoDTbXKOuZtp5RV0Xz0H8Nf6De6lK42LAMjSLiYr8P2Tw7nSdBqb7EoLj',
                'created_at' => '2018-01-08 13:02:15',
                'updated_at' => '2018-01-08 13:02:15',
            ),
            80 => 
            array (
                'id' => 96,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'cobabisaga@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$avWStJ/ez2bm8L/8A27o4.P9sV.yh/JHZDAXaAshnkNceJhPOYaGm',
                'verified' => 0,
                'email_token' => 'eyJpdiI6Imt6cW9tSmhvWHFsbDFsSkZKd2s5bVE9PSIsInZhbHVlIjoianN5U1RcL1htMUMyZ1dBNDF5YUc5bm5hMTIrdktWbWhCbDZpYXZEXC9RUTVNPSIsIm1hYyI6IjRiMDY3YjA4ZWY1NjE2MmJjMWZlNDE4ZDEwN2JlNjk0OWFjYWM0NGZlMWI1MGJiYjMwZGFlNGE2Y2M4ZTYwODQifQ==',
                'remember_token' => 'BHoxFOrPciHZugy4DPcaH6u5qzJ8kZfXsNpZKmgKxhFDUzNsXmegL7M0cJnT',
                'created_at' => '2018-01-08 13:08:20',
                'updated_at' => '2018-01-08 13:08:20',
            ),
            81 => 
            array (
                'id' => 97,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa80@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$g1vHCGmbPWZAAcmBsxN6iO8H.ggtReO6AW9DfXIxRFC2lFtGJpoDO',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IkxUOTN5d1RTRFZjT3R6TUVvWEZqaGc9PSIsInZhbHVlIjoiOXlnQWxYS2hzXC9GN1VzN0R1MWxRXC9rcU5cL3h0RlwvNzFaUFliWFFBWnh6NGM9IiwibWFjIjoiMmMxYjYyOGM2MDM1NjgyODdkNzM3NzIzOGY0ODRmM2UzZjI4YjExYTBhNmJjMTY2MDZiM2UzZTZkYmQ2YjUyMSJ9',
                'remember_token' => 'jhxgk3fqWL0GRqWnYLdF5ZQpxHBLLoy0FGDI6iOvgoCdKretiaP1LqjYhiPz',
                'created_at' => '2018-01-08 13:21:25',
                'updated_at' => '2018-01-08 13:21:25',
            ),
            82 => 
            array (
                'id' => 98,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa81@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$8owJwI8uoxLgD6JRQhN1NuLWGABsPX.ljt4Y.irNpLDnv0q1zxg9.',
                'verified' => 0,
                'email_token' => 'eyJpdiI6ImxYeHJlc3RlNXdhaVMxSWU5ZGhENUE9PSIsInZhbHVlIjoiSkI4eDBMemxERXE2RzUreTBQSkYwVU9vQXI3QUJvWmZPanBjMjkrWGloST0iLCJtYWMiOiI1MDNlMzNlYzcxMzc0NzUyYmMyNTFmMzI0NTRhMzk5ZWMxMWNhOTJlNTdjZWI0ZDgwZGY5MDNmMDM3YzkzNTRiIn0=',
                'remember_token' => 'Xfo8UMGAX7HE78ygy5G4nHGu2eFyAzxZqnwcdTAMFuUTJuLvBa5tQVZqxyTl',
                'created_at' => '2018-01-08 13:21:57',
                'updated_at' => '2018-01-08 13:21:57',
            ),
            83 => 
            array (
                'id' => 99,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa82@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$lpkthg.tuH/mbtoFWdJrR.nwFOZjJMVW7ykGh/bxsc3MmBelZNe.e',
                'verified' => 0,
                'email_token' => 'eyJpdiI6ImZLMk14OUlxS1Eza2JWUXJ3S0xGQ2c9PSIsInZhbHVlIjoibFo0cEE0ZXNnZXJ5R01rNm05RXFTS21uZlR2Z0prTko4WkxtYjRpSHV3ST0iLCJtYWMiOiJkMTcxZTM3ODg3MTZlMzk2MTc1YjU2N2Y3MTg4NTFjOTliNDdkZjhjZDNiOTkzYjc1ODU4YzY5NDMwNDA3OWE0In0=',
                'remember_token' => 'NH0DCzYIbR8DhNXPdodu1xxb9uv54X0ZQeaPPQyIq22PTl24oL3TIQBkgQ2A',
                'created_at' => '2018-01-08 13:22:39',
                'updated_at' => '2018-01-08 13:22:40',
            ),
            84 => 
            array (
                'id' => 100,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa83@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$ywQLKtCKWZGfbu5bTHJi3u/cYRaLY0oy78rhBG7ozcNq.7F71/rVW',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IkFqQ0syK0JGN1wvSksrbU9LSEFBTmVRPT0iLCJ2YWx1ZSI6IlhwOE9Xam9iSkxLN0pFdThhNnpZQldqQXJDc3hQbXdIbHJpWlI4b3VrZGM9IiwibWFjIjoiNzk5Y2Y2ZjQ3NDBkZDNmOGE2YzRmZjg3M2Y4Y2FkNTM5ZWJiNDc3MzM2MWY0NmFiN2E5ZmY4M2Y4MjMxNjEzYyJ9',
                'remember_token' => 'HhWeXSXouDx250PtkZkwpwKD6qbS6MHSo26GdlmyV790YS3nTPYmBmXdUYaa',
                'created_at' => '2018-01-08 13:28:47',
                'updated_at' => '2018-01-08 13:28:47',
            ),
            85 => 
            array (
                'id' => 101,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa84@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$ojtM5o9U45y6RBP8W4nPZOkEompEBgqqbz6g4Sdd.NnWDlCO2beaS',
                'verified' => 0,
                'email_token' => 'eyJpdiI6Ik9waktvd29GWGpaNDdhUkoxVnFINEE9PSIsInZhbHVlIjoiNmloaFlMTlFlMUpSRkcyRVBMRGJ3czdnNjBYSStCU216QnNzbFo4NUJvZz0iLCJtYWMiOiI5YzMzYzQ5ODkzMDFhYzUyY2I1NDM3ODkxNGY0Y2I0NGY0Y2FiZmY5MGMwZDFlNDgxMDJjYzJlODdkYTBmZTI4In0=',
                'remember_token' => 'PUo1ENwt5HLZD34qahaB9R7Dce1T3FEqgeO1CfL2q51LNnLOOeuLFJqIf9WR',
                'created_at' => '2018-01-08 13:30:18',
                'updated_at' => '2018-01-08 13:30:18',
            ),
            86 => 
            array (
                'id' => 102,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa85@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$tV5/HbAZWfEIWwgG6ypElOP/3TjXjvw5keXBfBlncuY7BgBTxHU2S',
                'verified' => 0,
                'email_token' => 'eyJpdiI6IkNVWGNtSWhycGxDOHdwWjk2bWI2dkE9PSIsInZhbHVlIjoiNFwvVFlEYmk4UFVNdHBJXC9hdjhFUXY1NVJqSDFaemxob2E2RXN6aENGTEtJPSIsIm1hYyI6IjQ5NWE0MTc0YjhiOGYwOTQ5MGVhY2NhZmEzNjg1N2RhODQzODlkNTJjOGQzZmY3MzdjOGQ4YjMyMTA3NTc2MmEifQ==',
                'remember_token' => 'm3qabKpoPebBd1QJOHLJK9e4T1IVtR3FnOSgKPFSNehx1rx0FReZhnhUddl2',
                'created_at' => '2018-01-08 13:39:04',
                'updated_at' => '2018-01-08 13:39:04',
            ),
            87 => 
            array (
                'id' => 103,
                'role_id' => 2,
                'cart_id' => NULL,
                'access_token_id' => NULL,
                'name' => 'Rizal Fakhri',
                'email' => 'bisa86@gmail.com',
                'avatar' => 'users/default.png',
                'password' => '$2y$10$ekeNW.ijWF0F1xuHgfi1LeQi1zFp7eCGHuRgU.xsAUlsKobXS3dGC',
                'verified' => 0,
                'email_token' => 'eyJpdiI6Ijd3N2t4OXJGSnh2WnhYbVVtSVg2Znc9PSIsInZhbHVlIjoiQ1UrY0xoY0lLdFFjZDRYRGxzcmpcLzdkWVprYTJrWktuMW81VmlucW5kOWM9IiwibWFjIjoiZmUyMDNlYTcxMWVmZTk4ZWM1MDgyNjQ4MzI3MDE4ZjEzZjJlNzI4ZWVkMjgwNjU2ZDMxZWEyMmMyZjQ3YzQ2MCJ9',
                'remember_token' => NULL,
                'created_at' => '2018-01-08 13:40:05',
                'updated_at' => '2018-01-08 13:40:05',
            ),
        ));
        
        
    }
}